import type { EnhancedLesson, LessonSource } from "./enhancedLessons";

const sources: LessonSource[] = [
  { title: "Oscilloscope Basics", publisher: "Tektronix", edition: "Current online primer", jurisdiction: "Manufacturer measurement guidance", url: "https://www.tek.com/en/documents/primer/oscilloscope-basics" },
  { title: "Setting Up and Using an Oscilloscope", publisher: "Tektronix", edition: "Current online primer", jurisdiction: "Manufacturer safety guidance", url: "https://www.tek.com/en/documents/primer/setting-and-using-oscilloscope" },
  { title: "381 Clamp Meter Users Manual", publisher: "Fluke", edition: "Current online manual", jurisdiction: "Manufacturer safety guidance", url: "https://assets.fluke.com/manuals/381_____umeng0000.pdf" },
];
type Draft = Omit<EnhancedLesson, "difficulty" | "sources" | "reviewDate" | "reviewStatus" | "localCode">;
const make = (draft: Draft): EnhancedLesson => ({ ...draft, difficulty: "Beginner", sources, reviewDate: "2026-08-21", reviewStatus: "professional-review-pending", localCode: "Instrument categories, proving-dead procedures, PPE, live-work permissions, and competent-person requirements vary by jurisdiction and task. Follow current local rules and the exact instrument manual." });

export const FUNDAMENTALS_MEASUREMENT_LESSONS: Record<string, EnhancedLesson> = {
  "electrical-fundamentals:l34": make({
    purpose: "Select multimeter function, connection, range, and measurement category for basic voltage and current work.", prerequisites: ["Voltage and current", "Series and parallel measurement"], objectives: ["Connect voltage in parallel", "Connect current in series", "Interpret AC/DC and true RMS", "Apply the lowest CAT rating in the measurement system"], introduction: "A multimeter changes its internal circuit with the selected function. Correct probe position and safe rating are as important as the displayed number.", theory: ["Voltage measurement presents high impedance across two points; current measurement routes circuit current through a low-resistance shunt.", "AC readings depend on bandwidth and method; average-responding meters may misread distorted waveforms, while true-RMS meters still have crest-factor limits.", "The safe system rating is limited by the lowest CAT and voltage rating of meter, leads, probes, and accessories."], terms: [{ term: "Measurement category", meaning: "Transient environment classification", symbol: "CAT" }, { term: "Burden voltage", meaning: "Voltage introduced by current measurement", unit: "V" }, { term: "True RMS", meaning: "Method calculating RMS within specified waveform limits" }], workedExample: { problem: "Measure a nominal 24 V DC control supply with a suitable meter.", assumptions: ["Competent safe access", "Meter and leads rated for the environment"], steps: [{ label: "Inspect", detail: "Check meter, leads, fuses, ratings, and a known source." }, { label: "Configure", detail: "Black lead COM, red lead voltage input, select DC volts and a suitable range." }, { label: "Connect", detail: "Probe across the two defined points, observe polarity, then remove safely." }], answer: "Use the voltage input and DC-voltage function in parallel across the defined points.", reasonableness: "A near-24 V result must be interpreted with supply tolerance and load state." }, commonMistakes: ["Leaving the red lead in the current socket", "Measuring current across a source", "Assuming CAT voltage alone describes all protection"], application: "Multimeters support commissioning, controls, electronics, and fault finding.", safety: "Prove the instrument on a known source before and after proving dead where required. Live measurement requires competence, PPE, safe access, and correctly rated equipment.", knowledgeCheck: { question: "Why is an ammeter connection across a voltage source dangerous?", answer: "Its low-resistance path can create very high fault current", feedback: "Current measurement belongs in series or uses a suitable clamp method." }, practicalExercise: "On a de-energised training setup, identify lead sockets and describe configurations for resistance, voltage, and current without energising it.", summary: ["Function and sockets must agree", "Voltage is parallel; current is series", "The lowest system rating governs"]
  }),
  "electrical-fundamentals:l35": make({
    purpose: "Use clamp-meter principles correctly, including single-conductor placement, waveform limits, and safe live-current practice.", prerequisites: ["Current", "Magnetic fields", "Measurement categories"], objectives: ["Clamp one conductor", "Explain cancellation", "Distinguish AC-only and AC/DC clamps", "Recognise leakage-current requirements"], introduction: "A clamp meter infers current from the magnetic field around a conductor, avoiding insertion of a shunt into the circuit.", theory: ["Clamping around both outgoing and return conductors normally cancels equal opposing fields; clamp one conductor for load current.", "Current transformers measure AC; Hall-effect sensors can measure AC and DC when zeroed correctly.", "Jaw closure, conductor centring, nearby fields, bandwidth, crest factor, and range affect accuracy."], terms: [{ term: "Clamp meter", meaning: "Instrument sensing conductor magnetic field" }, { term: "Hall sensor", meaning: "Field sensor capable of DC measurement" }, { term: "Leakage current", meaning: "Residual current found by enclosing all live conductors", unit: "A" }], workedExample: { problem: "A clamp around a two-core cable reads approximately zero although the load operates.", assumptions: ["Outgoing and return currents are equal"], steps: [{ label: "Explain", detail: "Opposing magnetic fields cancel inside the jaw." }, { label: "Correct", detail: "Separate and clamp one conductor using a safe breakout arrangement." }, { label: "Exception", detail: "Clamping all live conductors intentionally measures residual leakage with a suitable sensitive clamp." }], answer: "For load current, clamp one conductor; around both conductors the net field normally cancels.", reasonableness: "KCL predicts equal outgoing and returning load current." }, commonMistakes: ["Clamping an entire flex for load current", "Using an AC-only clamp for DC", "Opening jaws around unsafe exposed conductors"], application: "Clamp meters measure load, inrush, leakage, and circuit current without breaking the conductor.", safety: "Live clamping still places the operator near energized parts. Respect CAT/voltage rating, jaw clearances, PPE, access, and manufacturer instructions.", knowledgeCheck: { question: "Why does a clamp around line and neutral usually read near zero?", answer: "Their equal opposite currents produce cancelling magnetic fields", feedback: "Clamp one conductor for load current." }, practicalExercise: "Use a de-energised cable model to mark valid jaw positions for load-current and residual-leakage measurement.", summary: ["Clamp one conductor for load current", "Sensor type determines DC capability", "Live proximity remains hazardous"]
  }),
  "electrical-fundamentals:l36": make({
    purpose: "Read oscilloscope voltage-time displays while accounting for probe ratio, grounding, bandwidth, sampling, and circuit loading.", prerequisites: ["Waveform amplitude", "Frequency and period", "Phase"], objectives: ["Read axes and divisions", "Set probe attenuation consistently", "Use trigger controls", "Identify grounding hazards"], introduction: "An oscilloscope plots voltage vertically against time horizontally; an accurate display depends on instrument and probe setup.", theory: ["Volts/div and seconds/div convert screen divisions to amplitude and time. Frequency is reciprocal period.", "Probe attenuation must match the channel setting. Probe capacitance and bandwidth load and limit the measured signal.", "Trigger level and slope stabilise repetitive waveforms; sample rate and memory determine captured detail and aliasing risk."], terms: [{ term: "Timebase", meaning: "Horizontal time per division", unit: "s/div" }, { term: "Vertical scale", meaning: "Voltage per division", unit: "V/div" }, { term: "Trigger", meaning: "Condition that starts aligned acquisition" }, { term: "Aliasing", meaning: "False displayed frequency from insufficient sampling" }], formula: { expression: "Vpp=(vertical divisions)(V/div)(probe factor); f=1/T", explanation: "Confirm probe factor and calibrated scales before calculating.", units: "V, s, Hz" }, workedExample: { problem: "A 10× probe waveform spans 3.2 divisions at 0.5 V/div; one period spans 4 divisions at 0.5 ms/div.", assumptions: ["Channel setting has not already applied the probe factor"], steps: [{ label: "Voltage", detail: "Vpp=3.2×0.5×10=16 V." }, { label: "Period", detail: "T=4×0.5 ms=2.0 ms." }, { label: "Frequency", detail: "f=1/0.002=500 Hz." }], answer: "The waveform is 16 V peak-to-peak at 500 Hz.", reasonableness: "Two milliseconds per cycle gives 500 cycles per second." }, commonMistakes: ["Applying probe factor twice", "Clipping an earth-referenced probe ground to a live node", "Trusting an aliased display"], application: "Oscilloscopes reveal timing, noise, distortion, switching, phase, and transients.", safety: "A bench-scope ground clip is often earth-referenced. Connecting it to a live non-earth node can create a short circuit. Use a properly rated differential or isolated method where required.", knowledgeCheck: { question: "What causes aliasing?", answer: "Sampling too slowly to represent the signal", feedback: "The display may look stable while showing the wrong frequency." }, practicalExercise: "Interpret a safe simulator trace: calculate Vpp, period, and frequency, then list three setup details needed to trust it.", summary: ["Read scales and probe factor", "Trigger stabilises acquisition", "Grounding and sampling determine safety and truth"]
  }),
};
