import type { EnhancedLesson, LessonSource } from "./enhancedLessons";

const sources: LessonSource[] = [
  { title: "University Physics Volume 2: Capacitance, Inductance, and AC Circuits", publisher: "OpenStax", edition: "Current web edition", jurisdiction: "Physics reference", url: "https://openstax.org/books/university-physics-volume-2/pages/15-summary" },
  { title: "The International System of Units (SI Brochure)", publisher: "BIPM", edition: "9th edition, updated 2026", jurisdiction: "International", url: "https://www.bipm.org/en/publications/si-brochure" },
];
type Draft = Omit<EnhancedLesson, "difficulty" | "sources" | "reviewDate" | "reviewStatus" | "localCode">;
const make = (draft: Draft): EnhancedLesson => ({ ...draft, difficulty: "Beginner", sources, reviewDate: "2026-08-21", reviewStatus: "professional-review-pending", localCode: "The component relationships are universal. Product ratings, discharge provisions, protective measures, permitted work, and test procedures must follow current local rules and manufacturer data." });

export const FUNDAMENTALS_REACTIVE_LESSONS: Record<string, EnhancedLesson> = {
  "electrical-fundamentals:l29": make({
    purpose: "Relate capacitor construction, charge storage, geometry, voltage rating, and stored energy.", prerequisites: ["Charge", "Voltage", "Electric field"], objectives: ["Define capacitance", "Use Q=CV", "Predict geometry effects", "Calculate stored energy"], introduction: "A capacitor separates charge on conductors divided by a dielectric; it stores energy in the electric field rather than creating charge.", theory: ["Capacitance is charge per potential difference. Larger plate area and permittivity increase capacitance; larger spacing reduces it.", "Real capacitors have voltage, polarity, temperature, ripple-current, leakage, and tolerance limits.", "Stored energy is ½CV², so voltage has a squared effect."], terms: [{ term: "Capacitance", meaning: "Charge stored per volt", symbol: "C", unit: "farad (F)" }, { term: "Dielectric", meaning: "Insulating material between electrodes" }, { term: "Stored energy", meaning: "Energy in electric field", symbol: "E", unit: "J" }], formula: { expression: "Q=CV; E=½CV²", explanation: "Use farads, volts, coulombs, and joules.", units: "C, F, V, J" }, workedExample: { problem: "A 1000 µF capacitor is charged to 24 V. Find charge and energy.", assumptions: ["Capacitance is 0.001 F"], steps: [{ label: "Charge", detail: "Q=0.001×24=0.024 C." }, { label: "Energy", detail: "E=0.5×0.001×24²=0.288 J." }, { label: "Check", detail: "Doubling voltage would quadruple energy." }], answer: "Q=24 mC and E=0.288 J.", reasonableness: "The unit path gives coulombs and joules." }, commonMistakes: ["Leaving µF unconverted", "Assuming voltage rating is operating voltage", "Ignoring polarity on electrolytics"], application: "Capacitors filter supplies, start motors, couple signals, correct power factor, and store pulse energy.", safety: "Capacitors can retain hazardous voltage after isolation. Use a rated discharge method, verify voltage, and never short large capacitors casually.", knowledgeCheck: { question: "If voltage doubles at fixed capacitance, stored energy changes by what factor?", answer: "Four", feedback: "Energy depends on voltage squared." }, practicalExercise: "Calculate charge and energy for 47 µF at 12 V, showing prefix conversion.", summary: ["Capacitance is charge per volt", "Geometry and dielectric matter", "Stored energy scales with V²"]
  }),
  "electrical-fundamentals:l30": make({
    purpose: "Calculate capacitive reactance and explain why capacitor current leads voltage in sinusoidal operation.", prerequisites: ["Capacitance", "Frequency", "Phase"], objectives: ["Use XC formula", "Predict frequency effect", "State current lead", "Recognise non-ideal limits"], introduction: "A capacitor resists change in voltage. Under sinusoidal excitation this produces frequency-dependent reactance rather than a fixed DC resistance.", theory: ["XC=1/(2πfC), so higher frequency or capacitance lowers reactance.", "For an ideal capacitor, current leads voltage by 90° because current is proportional to the rate of voltage change.", "Real capacitors add equivalent series resistance, leakage, inductance, and ratings."], terms: [{ term: "Capacitive reactance", meaning: "Magnitude opposition of ideal capacitor", symbol: "XC", unit: "Ω" }, { term: "Leading current", meaning: "Current reaches corresponding phase earlier" }, { term: "ESR", meaning: "Equivalent series resistance representing loss", unit: "Ω" }], formula: { expression: "XC=1/(2πfC); I=V/XC", explanation: "Applies to sinusoidal steady-state magnitudes.", units: "Ω, Hz, F, A" }, workedExample: { problem: "Find reactance and current for 100 µF at 50 Hz on 24 V RMS.", assumptions: ["Ideal capacitor", "Sinusoidal source"], steps: [{ label: "Convert", detail: "C=100×10⁻⁶ F." }, { label: "Reactance", detail: "XC=1/(2π×50×100e−6)=31.83 Ω." }, { label: "Current", detail: "I=24/31.83=0.754 A RMS, leading." }], answer: "XC≈31.8 Ω and I≈0.754 A RMS leading voltage.", reasonableness: "A larger capacitance or frequency would yield more current." }, commonMistakes: ["Multiplying instead of taking reciprocal", "Using µF as F", "Saying a capacitor dissipates reactive power as heat"], application: "Capacitive reactance appears in filters, motor capacitors, coupling, and power-factor correction.", safety: "Power capacitors may carry substantial current and retain charge. Confirm discharge, fusing, voltage, ripple, and duty ratings.", knowledgeCheck: { question: "What happens to XC if frequency doubles?", answer: "It halves", feedback: "XC is inversely proportional to frequency." }, practicalExercise: "Calculate XC for 10 µF at 50 Hz and 1 kHz, then compare.", summary: ["XC falls as f or C rises", "Capacitor current leads voltage", "Real capacitors have loss and limits"]
  }),
  "electrical-fundamentals:l31": make({
    purpose: "Relate inductor construction, flux linkage, changing current, and stored magnetic energy.", prerequisites: ["Current", "Magnetic field", "Rate of change"], objectives: ["Define inductance", "Use v=L di/dt", "Predict core and turns effects", "Calculate stored energy"], introduction: "An inductor produces voltage when its current changes and stores energy in its magnetic field.", theory: ["Inductance links current change to induced voltage. More turns and suitable core permeability generally increase inductance.", "An ideal inductor passes steady DC after transients but opposes rapid current change.", "Real windings have resistance, core loss, capacitance, saturation, and thermal limits."], terms: [{ term: "Inductance", meaning: "Flux-linkage response to current", symbol: "L", unit: "henry (H)" }, { term: "Back emf", meaning: "Induced voltage opposing current change" }, { term: "Saturation", meaning: "Core region where flux no longer rises proportionally" }], formula: { expression: "v=L·di/dt; E=½LI²", explanation: "Polarity follows the chosen passive sign convention.", units: "V, H, A/s, J" }, workedExample: { problem: "A 0.20 H ideal inductor carries 3 A. Find stored energy.", assumptions: ["Linear unsaturated inductance"], steps: [{ label: "Square", detail: "I²=9 A²." }, { label: "Substitute", detail: "E=0.5×0.20×9." }, { label: "Calculate", detail: "E=0.90 J." }], answer: "Stored magnetic energy is 0.90 J.", reasonableness: "Energy is positive and scales with current squared." }, commonMistakes: ["Assuming zero winding resistance", "Treating inductance as constant through saturation", "Opening an energized coil without considering induced voltage"], application: "Inductors appear in relays, contactors, motors, transformers, filters, and converters.", safety: "Interrupting inductive current can create a high voltage and arc. Use suitable suppression, isolation, and discharge controls.", knowledgeCheck: { question: "What physical quantity can an ideal inductor current not change instantaneously?", answer: "Current", feedback: "Instantaneous current change would require unbounded voltage." }, practicalExercise: "Calculate energy in 50 mH at 2 A and predict the effect of doubling current.", summary: ["Inductors oppose current change", "Energy is magnetic", "Real cores and windings have limits"]
  }),
  "electrical-fundamentals:l32": make({
    purpose: "Calculate inductive reactance and explain why inductor current lags voltage in sinusoidal operation.", prerequisites: ["Inductance", "Frequency", "Phase"], objectives: ["Use XL formula", "Predict frequency effect", "State current lag", "Separate reactance from winding resistance"], introduction: "An ideal inductor's opposition grows with frequency because faster current change induces greater voltage.", theory: ["XL=2πfL, so reactance rises directly with frequency and inductance.", "For an ideal inductor, current lags voltage by 90°.", "A practical coil impedance includes winding resistance and core effects, not XL alone."], terms: [{ term: "Inductive reactance", meaning: "Magnitude opposition of ideal inductor", symbol: "XL", unit: "Ω" }, { term: "Lagging current", meaning: "Current reaches corresponding phase later" }, { term: "Coil impedance", meaning: "Combined winding resistance and reactance", symbol: "Z", unit: "Ω" }], formula: { expression: "XL=2πfL; I=V/XL", explanation: "Ideal sinusoidal steady-state relationship.", units: "Ω, Hz, H, A" }, workedExample: { problem: "A 0.10 H ideal inductor is connected to 24 V RMS at 50 Hz.", assumptions: ["Sinusoidal source", "Negligible winding resistance"], steps: [{ label: "Reactance", detail: "XL=2π×50×0.10=31.42 Ω." }, { label: "Current", detail: "I=24/31.42=0.764 A RMS." }, { label: "Phase", detail: "Current lags voltage by 90°." }], answer: "XL≈31.4 Ω and I≈0.764 A RMS lagging.", reasonableness: "The magnitude acts like 31.4 Ω in I=V/X, but it is not heat-producing resistance." }, commonMistakes: ["Using the capacitive reciprocal formula", "Saying current leads", "Ignoring winding resistance"], application: "Inductive reactance shapes motor, transformer, choke, solenoid, and filter currents.", safety: "Coils can overheat, saturate, and generate switching transients. Confirm frequency, voltage, duty, temperature, and suppression ratings.", knowledgeCheck: { question: "What happens to XL when frequency doubles?", answer: "It doubles", feedback: "XL is directly proportional to frequency." }, practicalExercise: "Calculate XL for 20 mH at 50 Hz and 500 Hz and compare currents at fixed voltage.", summary: ["XL rises with f and L", "Inductor current lags", "Real coil impedance includes resistance"]
  }),
  "electrical-fundamentals:l33": make({
    purpose: "Use RC and RL time constants to predict first-order charging and current transients.", prerequisites: ["Capacitance", "Inductance", "Exponential idea"], objectives: ["Calculate τRC and τRL", "Use 63.2% and 36.8% landmarks", "Estimate five-time-constant settling", "Respect initial continuity conditions"], introduction: "First-order circuits do not jump directly between steady states: capacitor voltage and inductor current change exponentially.", theory: ["For RC, τ=RC; a charging capacitor reaches 63.2% of final voltage after one τ.", "For RL, τ=L/R; current reaches 63.2% of final value after one τ.", "After about 5τ, remaining error is below 1%, though never mathematically zero."], terms: [{ term: "Time constant", meaning: "Characteristic exponential response time", symbol: "τ", unit: "s" }, { term: "Initial condition", meaning: "Stored voltage or current at switching" }, { term: "Steady state", meaning: "Long-time limiting condition" }], formula: { expression: "τRC=RC; τRL=L/R", explanation: "R is the resistance seen by the storage element.", units: "s" }, workedExample: { problem: "A 10 kΩ resistor charges a 100 µF capacitor from 0 V toward 12 V.", assumptions: ["Ideal source", "No other loading"], steps: [{ label: "Constant", detail: "τ=10,000×100e−6=1.0 s." }, { label: "One tau", detail: "Vc=0.632×12=7.58 V at 1 s." }, { label: "Settling", detail: "About 5 s reaches over 99% of final." }], answer: "τ=1.0 s; Vc≈7.58 V at 1 s; near-settled after about 5 s.", reasonableness: "Voltage changes quickly first and slows near 12 V." }, commonMistakes: ["Using µF without conversion", "Assuming 1τ means fully charged", "Using total resistance without finding what the element sees"], application: "Time constants govern delays, debounce, filters, coil release, soft starts, and transient measurements.", safety: "Stored capacitor energy and inductive current can persist or create transients after switching. Apply verified discharge and suppression methods.", knowledgeCheck: { question: "Approximately what fraction of final value is reached after one charging time constant?", answer: "63.2%", feedback: "The remaining error is e⁻¹≈36.8%." }, practicalExercise: "Find τ and 5τ for 47 kΩ with 10 µF, then sketch the charging landmarks.", summary: ["RC uses RC; RL uses L/R", "One τ reaches 63.2%", "Five τ is a practical settling estimate"]
  }),
};
