import type { EnhancedLesson, LessonSource } from "./enhancedLessons";

const sources: LessonSource[] = [
  { title: "The International System of Units (SI Brochure)", publisher: "BIPM", edition: "9th edition, updated 2026", jurisdiction: "International", url: "https://www.bipm.org/en/publications/si-brochure" },
  { title: "SI Units: Electric Current", publisher: "NIST", edition: "Current web edition", jurisdiction: "United States / SI reference", url: "https://www.nist.gov/pml/owm/si-units-electric-current" },
  { title: "University Physics Volume 2", publisher: "OpenStax", edition: "Current web edition", jurisdiction: "Physics reference", url: "https://openstax.org/details/books/university-physics-volume-2" },
];

type Draft = Omit<EnhancedLesson, "difficulty" | "sources" | "reviewDate" | "reviewStatus" | "localCode"> & { localCode?: string };
const lesson = (draft: Draft): EnhancedLesson => ({
  ...draft,
  difficulty: "Beginner",
  sources,
  reviewDate: "2026-08-21",
  reviewStatus: "professional-review-pending",
  localCode: draft.localCode ?? "The physical relationships are universal. Installation methods, permitted work, test procedures, and equipment ratings must be checked against current local rules and manufacturer instructions.",
});

export const FUNDAMENTALS_GROUP_ONE: Record<string, EnhancedLesson> = {
  "electrical-fundamentals:l1": lesson({
    purpose: "Build a useful atomic model for electrical work without implying that current is simply electrons racing from source to load.", prerequisites: ["No prior electrical knowledge", "Basic idea of matter"],
    objectives: ["Identify proton, neutron, and electron charge", "Distinguish atomic structure from a circuit model", "Explain mobile charge carriers in metals", "Relate charge imbalance to electrical effects"],
    introduction: "Electrical behaviour begins with charge. The atomic model explains why some particles are bound and why outer electrons in metals can respond collectively to an electric field.",
    theory: ["A neutral atom contains equal total positive and negative charge. Protons are positively charged, electrons negatively charged, and neutrons have no net charge.", "In a metallic conductor, some outer electrons occupy states that extend through the material. An applied electric field produces a small net drift superimposed on their thermal motion.", "The field establishing circuit behaviour propagates through the circuit far faster than the individual electrons drift; the source transfers energy through the electromagnetic system."],
    terms: [{term:"Proton",meaning:"Positively charged particle in an atomic nucleus"},{term:"Electron",meaning:"Negatively charged particle and common carrier in metals",symbol:"e⁻"},{term:"Electric field",meaning:"Field that exerts force on charge",symbol:"E",unit:"V/m"}],
    workedExample:{problem:"A body loses 2.0 × 10¹² electrons. Determine the sign and magnitude of its net charge.",assumptions:["Elementary charge magnitude is 1.602176634 × 10⁻¹⁹ C","No other charge transfer occurs"],steps:[{label:"Direction",detail:"Losing negative electrons leaves positive net charge."},{label:"Multiply",detail:"Q = n e = (2.0 × 10¹²)(1.602176634 × 10⁻¹⁹ C)."},{label:"Round",detail:"Q = +3.2 × 10⁻⁷ C = +0.32 µC."}],answer:"The body carries approximately +0.32 µC.",reasonableness:"A macroscopic coulomb represents an enormous number of elementary charges, so trillions of electrons still produce less than one microcoulomb."},
    commonMistakes:["Treating the Bohr picture as a literal circuit diagram","Saying neutrons are negatively charged","Assuming electron drift speed equals signal propagation speed"], application:"The carrier model helps explain conductors, semiconductors, static charge, and why a complete electric field path matters.", safety:"Static charge can ignite flammable atmospheres and damage electronics. Do not use classroom static demonstrations near fuels, dust hazards, sensitive devices, or medical equipment.", knowledgeCheck:{question:"Why can a lamp respond quickly even though electron drift is slow?",answer:"The circuit electric field is established through the system much faster than individual electrons drift",feedback:"Energy transfer is not explained by one electron travelling from the source to the lamp."}, practicalExercise:"Draw a neutral atom and a positively charged atom, then annotate what changed and what did not change in the nucleus.", summary:["Charge is a property of particles","Metals provide mobile carriers","Field propagation and carrier drift are different"]
  }),
  "electrical-fundamentals:l2": lesson({
    purpose:"Quantify electric charge in coulombs and connect charge to current and elementary particles.", prerequisites:["Atomic charge model","Scientific notation"], objectives:["Define the coulomb", "Use Q = It", "Use the exact elementary charge", "Convert between C, mC, and µC"], introduction:"The coulomb measures an amount of electric charge; the ampere measures how quickly that charge passes a reference point.", theory:["In SI, one coulomb equals one ampere-second. Charge is conserved: it may move or separate, but an isolated system does not create net charge.","The elementary charge magnitude is exactly 1.602176634 × 10⁻¹⁹ C. Electron charge is −e and proton charge is +e.","Charge values in circuits are often derived from current over time rather than by counting carriers."], terms:[{term:"Electric charge",meaning:"Quantity describing electrical interaction",symbol:"Q",unit:"coulomb (C)"},{term:"Elementary charge",meaning:"Magnitude of proton or electron charge",symbol:"e",unit:"C"},{term:"Ampere-second",meaning:"Charge transferred by one ampere in one second",unit:"A·s = C"}], formula:{expression:"Q = I × t",explanation:"Charge equals current multiplied by elapsed time.",units:"C = A·s"}, workedExample:{problem:"A 250 mA circuit operates for 40 s. How much charge passes?",assumptions:["Current is constant"],steps:[{label:"Convert",detail:"250 mA = 0.250 A."},{label:"Substitute",detail:"Q = 0.250 A × 40 s."},{label:"Calculate",detail:"Q = 10 A·s = 10 C."}],answer:"10 C of charge passes.",reasonableness:"A quarter coulomb per second for forty seconds gives ten coulombs."}, commonMistakes:["Treating coulomb as current","Skipping milli-to-base conversion","Using electron charge without its negative sign when direction matters"], application:"Battery capacity, electroplating, sensing, and fault-energy discussions all depend on charge transferred over time.", safety:"Even modest transferred charge can be hazardous when delivered at dangerous voltage or through the body. Charge alone is not a complete measure of electrical risk.", knowledgeCheck:{question:"What current transfers 6 C in 3 s?",answer:"2 A",feedback:"Rearrange Q = It to I = Q/t."}, practicalExercise:"Calculate charge for 20 mA over 5 min, showing both time and current conversions.", summary:["One coulomb is one ampere-second","Elementary charge has an exact SI value","Convert prefixes before calculating"]
  }),
  "electrical-fundamentals:l3": lesson({
    purpose:"Compare conductors, insulators, and semiconductors through available charge carriers and energy structure.", prerequisites:["Atomic model","Electric charge"], objectives:["Classify materials by electrical behaviour","Explain why copper conducts","Explain why insulation can break down","Describe controllable semiconductor conductivity"], introduction:"Material labels describe behaviour under stated conditions, not absolute categories: temperature, field strength, contamination, light, and doping can change conductivity.", theory:["Conductors contain carriers able to respond readily to an electric field; metals mainly use electrons, while electrolytes use ions.","Insulators strongly restrict carrier motion, but a sufficiently large electric field can cause dielectric breakdown and a conductive path.","Semiconductors have conductivity between typical conductors and insulators, adjustable through doping, temperature, light, and electric fields."], terms:[{term:"Conductivity",meaning:"Ability of a material to conduct current",symbol:"σ",unit:"S/m"},{term:"Insulator",meaning:"Material with very low conductivity under stated conditions"},{term:"Semiconductor",meaning:"Material whose carrier population can be controlled"},{term:"Breakdown",meaning:"Loss of insulation under excessive electric stress"}], workedExample:{problem:"Choose copper, dry PVC, or silicon for a cable conductor, its insulation, and a controllable sensor element.",assumptions:["Normal rated temperature and voltage"],steps:[{label:"Conductor",detail:"Copper provides high conductivity and practical mechanical properties."},{label:"Insulation",detail:"Dry PVC restricts current when used within its rating."},{label:"Sensor",detail:"Silicon conductivity can be engineered and controlled."}],answer:"Copper conductor, PVC insulation, silicon sensor.",reasonableness:"Each material is selected for a different carrier response rather than appearance."}, commonMistakes:["Calling insulation perfectly nonconductive","Assuming all liquids conduct","Confusing semiconductor with a poor-quality conductor"], application:"Cable construction, sensors, power electronics, and insulation testing depend on these material differences.", safety:"Damaged, wet, contaminated, overheated, or over-voltaged insulation may conduct. Never infer isolation from material appearance; prove dead using an approved procedure.", knowledgeCheck:{question:"Why may an insulator conduct after excessive voltage?",answer:"The electric field can exceed its dielectric strength and cause breakdown",feedback:"Insulation is rated for conditions; it is not an infinite barrier."}, practicalExercise:"Classify six household or workshop materials, then state the condition that could make each classification unsafe or misleading.", summary:["Conductivity depends on carriers and conditions","Insulators can break down","Semiconductor conductivity is deliberately controllable"]
  }),
  "electrical-fundamentals:l4": lesson({
    purpose:"Use conventional current direction consistently while relating it correctly to electron drift in metals.", prerequisites:["Charge signs","Current as charge movement"], objectives:["Define conventional current direction","State electron drift direction in a metal","Apply one sign convention consistently","Recognise other charge carriers"], introduction:"Circuit theory chose current direction before the electron was identified. The convention remains useful and does not make circuit equations wrong.", theory:["Conventional current is the direction positive charge would move: from higher potential toward lower potential through a passive external circuit.","In metals, negatively charged electrons drift opposite to conventional current. In electrolytes and semiconductors, multiple positive and negative carriers may contribute.","Schematics, meters, and component equations use reference directions. A negative calculated current means actual direction is opposite the chosen arrow."], terms:[{term:"Conventional current",meaning:"Reference direction for positive charge flow",symbol:"I",unit:"A"},{term:"Electron drift",meaning:"Small net electron motion opposite conventional current in a metal"},{term:"Reference direction",meaning:"Chosen arrow used to assign a sign to current"}], workedExample:{problem:"An arrow defines current left-to-right, but analysis gives I = −0.40 A. Interpret the result and electron drift in a copper wire.",assumptions:["Metallic conduction"],steps:[{label:"Interpret sign",detail:"Negative means conventional current is 0.40 A right-to-left."},{label:"Electron direction",detail:"Electrons drift opposite, left-to-right."},{label:"Retain convention",detail:"Do not change equations mid-solution; report the sign meaning."}],answer:"Conventional current is 0.40 A right-to-left; electron drift is left-to-right.",reasonableness:"The two directions oppose because electrons carry negative charge."}, commonMistakes:["Calling conventional direction incorrect","Reversing arrows midway through a calculation","Assuming every material conducts only by electrons"], application:"Reference arrows make measurements, Kirchhoff equations, semiconductor symbols, and control diagrams unambiguous.", safety:"Direction conventions do not indicate whether a conductor is safe to touch. Isolation, voltage, available fault current, and energy determine the required controls.", knowledgeCheck:{question:"A positive current result means what?",answer:"Actual conventional current follows the selected reference arrow",feedback:"The arrow is a sign convention; a negative result would indicate the opposite direction."}, practicalExercise:"Draw a cell and resistor loop with arrows for conventional current and electron drift, then mark the high- and low-potential terminals.", summary:["Conventional current follows positive-charge direction","Metal electrons drift oppositely","Negative results reverse the chosen reference"]
  }),
  "electrical-fundamentals:l11": lesson({
    purpose:"Analyse series resistors using shared current, additive voltage drops, and equivalent resistance.", prerequisites:["Ohm's law","Closed circuits"], objectives:["Identify a true series path","Calculate series equivalent resistance","Find individual voltage drops","Check voltage and power balance"], introduction:"Components are in series only when the same current must pass through each one with no branching node between them.", theory:["Series equivalent resistance is the sum of individual resistances because their voltage drops add for the same current.","The supply voltage divides in proportion to resistance for linear resistors.","Opening any point in a single series path stops current throughout that path."], terms:[{term:"Series connection",meaning:"Components sharing one unbranched current path"},{term:"Equivalent resistance",meaning:"Single resistance with the same terminal behaviour",symbol:"Req",unit:"Ω"},{term:"Voltage drop",meaning:"Potential difference across a passive component",symbol:"V",unit:"V"}], formula:{expression:"Req = R₁ + R₂ + …;  Vₙ = I Rₙ",explanation:"Add series resistances, calculate loop current, then each drop.",units:"Ω and V"}, workedExample:{problem:"A 12 V source feeds 100 Ω and 200 Ω in series.",assumptions:["Ideal 12 V source","Linear resistors"],steps:[{label:"Equivalent",detail:"Req = 100 + 200 = 300 Ω."},{label:"Current",detail:"I = 12/300 = 0.040 A."},{label:"Drops",detail:"V₁ = 4 V and V₂ = 8 V; total = 12 V."}],answer:"Req = 300 Ω, I = 40 mA, drops are 4 V and 8 V.",reasonableness:"The larger resistor receives twice the drop, and the drops equal the supply."}, commonMistakes:["Calling components series when a branch exists","Adding conductances instead of resistances","Forgetting to verify voltage sum"], application:"Series elements appear in sensing chains, LED current limiting, measurement circuits, and voltage dividers.", safety:"A series calculation does not guarantee adequate resistor voltage, power, impulse, or insulation ratings. Confirm every component rating.", knowledgeCheck:{question:"Three series resistors carry 2 A. What current passes through the middle resistor?",answer:"2 A",feedback:"There is no branch where current can divide."}, practicalExercise:"Analyse 5 V with 150 Ω and 350 Ω, then verify current, both drops, and total power.", summary:["Series means one current path","Resistances and voltage drops add","Use balance checks"]
  }),
  "electrical-fundamentals:l12": lesson({
    purpose:"Analyse parallel resistors using common voltage, branch current, and reciprocal equivalent resistance.", prerequisites:["Ohm's law","Series circuits","Fractions"], objectives:["Identify common-node parallel branches","Calculate parallel equivalent resistance","Find branch currents","Check total current and power"], introduction:"Parallel components connect across the same two nodes, so every branch has the same voltage while current divides by branch resistance.", theory:["Parallel conductances add: 1/Req = Σ(1/Rn). Equivalent resistance is lower than the smallest positive branch resistance.","Total current is the sum of branch currents, consistent with charge conservation at each node.","Adding a parallel load lowers equivalent resistance and increases source current for a fixed ideal voltage."], terms:[{term:"Parallel connection",meaning:"Branches connected to the same two nodes"},{term:"Branch current",meaning:"Current in one parallel path",symbol:"Iₙ",unit:"A"},{term:"Conductance",meaning:"Reciprocal of resistance",symbol:"G",unit:"siemens (S)"}], formula:{expression:"1/Req = 1/R₁ + 1/R₂ + …;  It = ΣIₙ",explanation:"Add reciprocal resistances and add branch currents.",units:"Ω, S, and A"}, workedExample:{problem:"Connect 6 Ω and 3 Ω across 12 V.",assumptions:["Ideal source","Linear resistors"],steps:[{label:"Equivalent",detail:"1/Req = 1/6 + 1/3 = 1/2, so Req = 2 Ω."},{label:"Branches",detail:"I₁ = 12/6 = 2 A; I₂ = 12/3 = 4 A."},{label:"Check",detail:"It = 6 A and 12/2 = 6 A."}],answer:"Req = 2 Ω; branch currents 2 A and 4 A; total 6 A.",reasonableness:"Equivalent resistance is below 3 Ω and the lower-resistance branch carries more current."}, commonMistakes:["Adding parallel resistances directly","Assuming branch currents are equal with unequal resistance","Accepting Req greater than the smallest branch"], application:"Building circuits, socket loads, lighting branches, and electronic bias networks commonly operate in parallel.", safety:"Adding parallel loads can overload a source or conductor even though each load voltage stays unchanged. Protective coordination and conductor capacity still matter.", knowledgeCheck:{question:"What must be equal for ideal parallel branches?",answer:"Voltage across each branch",feedback:"Their endpoints are the same two nodes."}, practicalExercise:"Calculate equivalent resistance and branch currents for 24 Ω and 8 Ω across 24 V.", summary:["Parallel branches share voltage","Branch currents add","Equivalent resistance is below the smallest branch"]
  }),
  "electrical-fundamentals:l13": lesson({
    purpose:"Reduce series-parallel resistor networks without combining components that do not share the required topology.", prerequisites:["Series rules","Parallel rules","Ohm's law"], objectives:["Mark circuit nodes","Identify reducible groups","Work from inner groups outward","Expand results to branch quantities"], introduction:"Combined networks become manageable when topology is read from nodes rather than from how close components appear on a drawing.", theory:["Two components are parallel only if both ends connect to the same two nodes. They are series only if their shared node has no other current path.","Reduce one valid group to an equivalent, redraw mentally or on paper, and repeat.","After total current is known, reverse the reductions to recover voltages and branch currents."], terms:[{term:"Node",meaning:"Set of conductively connected points at one ideal potential"},{term:"Reduction",meaning:"Replacement of a subnetwork by an equivalent"},{term:"Topology",meaning:"Connection relationships independent of drawing shape"}], formula:{expression:"Reduce: series ΣR; parallel (Σ1/R)⁻¹",explanation:"Apply only to groups verified by their nodes.",units:"Ω"}, workedExample:{problem:"A 4 Ω resistor is in series with a parallel pair of 6 Ω and 3 Ω on 12 V.",assumptions:["Ideal source and wires"],steps:[{label:"Parallel group",detail:"6 Ω || 3 Ω = 2 Ω."},{label:"Total",detail:"Req = 4 + 2 = 6 Ω; It = 12/6 = 2 A."},{label:"Expand",detail:"Drop on 4 Ω is 8 V, leaving 4 V across the parallel pair; branches are 0.667 A and 1.333 A."}],answer:"Req = 6 Ω and source current = 2 A.",reasonableness:"Branch currents total 2 A and voltage drops total 12 V."}, commonMistakes:["Combining components based on drawing position","Failing to redraw after reduction","Rounding intermediate values too early"], application:"Reduction supports sensor networks, load banks, bias circuits, and preliminary fault reasoning.", safety:"De-energise before resistance measurements. Connected sources or charged components can damage a meter and expose the operator to hazardous energy.", knowledgeCheck:{question:"What proves two resistors are parallel?",answer:"Both terminals of each connect to the same two nodes",feedback:"Visual alignment alone is insufficient."}, practicalExercise:"Solve 10 Ω in series with 20 Ω || 30 Ω on 22 V and verify both conservation checks.", summary:["Read nodes, not drawing proximity","Reduce one valid group at a time","Reverse the reduction to recover branch values"]
  }),
  "electrical-fundamentals:l14": lesson({
    purpose:"Use unloaded voltage dividers and two-branch current dividers while recognising loading limits.", prerequisites:["Series and parallel networks","Ratios","Ohm's law"], objectives:["Calculate divider output voltage","Calculate two-branch current division","Explain loading error","Check limiting cases"], introduction:"Divider rules are shortcuts derived from series and parallel laws; they are valid only when their assumptions match the circuit.", theory:["For two series resistors, the unloaded output across R₂ is Vin R₂/(R₁+R₂). A connected load sits in parallel with R₂ and changes the ratio.","For two parallel resistors, current through R₁ equals total current times R₂/(R₁+R₂); current favours the lower resistance.","Divider networks dissipate power continuously and often need buffering when driving a load."], terms:[{term:"Voltage divider",meaning:"Series network producing a fraction of input voltage"},{term:"Current divider",meaning:"Parallel network splitting total current"},{term:"Loading",meaning:"Output change caused by a connected load"}], formula:{expression:"Vout = Vin·R₂/(R₁+R₂); I₁ = It·R₂/(R₁+R₂)",explanation:"The current-divider numerator uses the other branch resistance.",units:"V and A"}, workedExample:{problem:"A 10 kΩ/5 kΩ unloaded divider is connected across 15 V; output is across 5 kΩ.",assumptions:["Output load impedance is effectively infinite"],steps:[{label:"Ratio",detail:"R₂/(R₁+R₂) = 5/(10+5) = 1/3."},{label:"Output",detail:"Vout = 15 × 1/3 = 5 V."},{label:"Check",detail:"Series current is 1 mA; drops are 10 V and 5 V."}],answer:"The unloaded output is 5 V.",reasonableness:"The lower resistor is one-third of total resistance, so it receives one-third of the voltage."}, commonMistakes:["Ignoring load resistance","Using the wrong resistor in the numerator","Applying current division to series components"], application:"Dividers scale sensor signals, establish reference levels, and estimate branch currents, but precision designs account for tolerance and loading.", safety:"A divider is not protective isolation and must not be used to make hazardous mains safe for touch or low-voltage electronics without approved isolation and protection.", knowledgeCheck:{question:"What happens when a finite load is added across the lower divider resistor?",answer:"Its effective resistance falls and the output voltage usually falls",feedback:"The load is parallel with the lower resistor."}, practicalExercise:"Calculate a 9 V divider using 2 kΩ and 1 kΩ, then repeat with a 1 kΩ load across the lower resistor.", summary:["Divider rules come from network laws","Loading changes voltage division","A divider does not provide isolation"]
  }),
};