import type { EnhancedLesson, LessonSource } from "./enhancedLessons";

const sources: LessonSource[] = [
  { title: "University Physics Volume 2 — Alternating-Current Circuits", publisher: "OpenStax", edition: "Current web edition", jurisdiction: "Physics reference", url: "https://openstax.org/books/university-physics-volume-2/pages/15-summary" },
  { title: "The International System of Units (SI Brochure)", publisher: "BIPM", edition: "9th edition, updated 2026", jurisdiction: "International", url: "https://www.bipm.org/en/publications/si-brochure" },
];
type Draft = Omit<EnhancedLesson, "difficulty" | "sources" | "reviewDate" | "reviewStatus" | "localCode">;
const make = (draft: Draft): EnhancedLesson => ({ ...draft, difficulty: "Beginner", sources, reviewDate: "2026-08-21", reviewStatus: "professional-review-pending", localCode: "The physics and SI relationships are universal. Nominal frequency, supply characteristics, permitted work, and instrument requirements must be confirmed for the actual jurisdiction and task." });

export const FUNDAMENTALS_AC_LESSONS: Record<string, EnhancedLesson> = {
  "electrical-fundamentals:l24": make({
    purpose: "Compare AC and DC accurately and explain the transmission advantage of transformable voltage without a simplistic winner narrative.", prerequisites: ["Voltage and current", "Power loss"], objectives: ["Define AC and DC", "Describe polarity reversal", "Explain high-voltage transmission loss reduction", "Recognise modern AC and DC applications"],
    introduction: "AC and DC describe how voltage and current vary with time. Modern power systems use both, chosen for generation, conversion, storage, transmission, and load needs.",
    theory: ["DC maintains one current reference direction although magnitude may vary; AC periodically reverses direction.", "Transformers made sinusoidal AC voltage conversion practical, allowing transmission at high voltage and lower current for the same power, reducing I²R loss.", "Power electronics now convert efficiently between AC and DC, so batteries, solar arrays, HVDC links, drives, and grids coexist."],
    terms: [{ term: "Direct current", meaning: "Current retaining one reference direction", symbol: "DC" }, { term: "Alternating current", meaning: "Current that periodically reverses", symbol: "AC" }, { term: "Transmission loss", meaning: "Resistive line heating", unit: "W" }],
    formula: { expression: "Ploss = I²R; for fixed P, higher V permits lower I", explanation: "This is the core transmission argument; conversion equipment and system constraints also matter.", units: "W, V, A, Ω" },
    workedExample: { problem: "Transmit 10 kW through 2 Ω total line resistance at 100 V or 1000 V, neglecting conversion loss.", assumptions: ["Unity power factor", "Fixed line resistance"], steps: [{ label: "Currents", detail: "I100=100 A; I1000=10 A." }, { label: "Losses", detail: "Losses are 20 kW and 200 W respectively." }, { label: "Compare", detail: "Tenfold voltage reduces current tenfold and I²R loss hundredfold." }], answer: "The 1000 V case has 200 W line loss versus 20 kW at 100 V.", reasonableness: "Loss follows current squared; the low-voltage case is deliberately impractical because loss exceeds delivered power." },
    commonMistakes: ["Saying AC is always superior", "Defining DC as perfectly constant", "Ignoring conversion and insulation constraints"], application: "Grids, electronic supplies, batteries, variable-speed drives, and HVDC links combine both forms.", safety: "Both AC and DC can cause lethal shock, burns, and arcs. DC arcs may be difficult to interrupt; never infer safety from waveform type.", knowledgeCheck: { question: "Why does raising transmission voltage reduce conductor loss for the same transferred power?", answer: "It lowers current, and resistive loss varies with current squared", feedback: "Use P≈VI and Ploss=I²R." }, practicalExercise: "Compare line loss for one fixed power at three voltages and state the assumptions behind the comparison.", summary: ["AC reverses; DC retains direction", "High voltage reduces current for fixed power", "Modern systems use AC and DC"]
  }),
  "electrical-fundamentals:l25": make({
    purpose: "Relate sine-wave peak, peak-to-peak, average, and RMS quantities without applying sine factors to arbitrary waveforms.", prerequisites: ["AC definition", "Squares and square roots"], objectives: ["Read sine-wave amplitude", "Calculate RMS", "Distinguish cycle average from rectified average", "State waveform assumptions"], introduction: "A changing waveform needs a declared measure. RMS expresses heating equivalence, while peak values determine insulation and device stress.",
    theory: ["For a pure sine wave, Vrms=Vpk/√2 and Vpp=2Vpk.", "A symmetrical sine wave averages to zero over a full cycle; the average of its rectified magnitude is 2Vpk/π.", "RMS is defined from the square, mean, then square root, so non-sinusoidal waveforms require their actual shape or a true-RMS instrument."], terms: [{ term: "Peak", meaning: "Maximum magnitude from zero reference", symbol: "Vpk", unit: "V" }, { term: "Peak-to-peak", meaning: "Maximum minus minimum", symbol: "Vpp", unit: "V" }, { term: "RMS", meaning: "Root-mean-square effective value", symbol: "Vrms", unit: "V" }], formula: { expression: "Sine: Vrms=Vpk/√2; Vpp=2Vpk", explanation: "These ratios apply to an undistorted sine wave.", units: "V" },
    workedExample: { problem: "A sine source measures 230 V RMS. Find peak and peak-to-peak voltage.", assumptions: ["Pure sinusoid"], steps: [{ label: "Peak", detail: "Vpk=230√2=325.3 V." }, { label: "Peak-to-peak", detail: "Vpp=2×325.3=650.5 V." }, { label: "Round", detail: "About 325 V peak and 651 V peak-to-peak." }], answer: "Vpk≈325 V and Vpp≈651 V.", reasonableness: "RMS is about 70.7% of sine peak." }, commonMistakes: ["Calling 230 V the peak", "Using √2 for square waves", "Confusing full-cycle average with RMS"], application: "RMS supports power calculations; peak governs semiconductor, insulation, and probe stress.", safety: "A 230 V RMS sine wave reaches about 325 V peak. Instruments, leads, probes, and insulation must suit the actual peak and transient environment.", knowledgeCheck: { question: "A 10 V peak sine wave has what RMS value?", answer: "Approximately 7.07 V", feedback: "Divide sine peak by √2." }, practicalExercise: "Calculate RMS and peak-to-peak for a 24 V peak sine wave, then explain why the full-cycle average is zero.", summary: ["Declare the waveform measure", "Sine RMS is peak divided by √2", "Peak stress differs from RMS heating"]
  }),
  "electrical-fundamentals:l26": make({
    purpose: "Calculate frequency, period, and angular frequency using consistent time units.", prerequisites: ["Periodic waveforms", "Unit prefixes"], objectives: ["Define one cycle", "Use T=1/f", "Convert milliseconds", "Calculate angular frequency"], introduction: "Frequency counts repeated cycles each second; period measures the time for one cycle. They are reciprocals, not independent properties.", theory: ["The hertz is one cycle per second. Period is measured in seconds.", "Angular frequency ω=2πf expresses phase progress in radians per second.", "Real grids have a nominal frequency with controlled variation; electronic signals may span millihertz to gigahertz."], terms: [{ term: "Frequency", meaning: "Cycles per second", symbol: "f", unit: "hertz (Hz)" }, { term: "Period", meaning: "Time for one cycle", symbol: "T", unit: "s" }, { term: "Angular frequency", meaning: "Phase rate", symbol: "ω", unit: "rad/s" }], formula: { expression: "T=1/f; f=1/T; ω=2πf", explanation: "Convert prefixes before taking a reciprocal.", units: "s, Hz, rad/s" }, workedExample: { problem: "Find period and angular frequency for 50 Hz.", assumptions: ["Stable periodic waveform"], steps: [{ label: "Period", detail: "T=1/50=0.020 s=20 ms." }, { label: "Angular", detail: "ω=2π×50=314.16 rad/s." }, { label: "Check", detail: "50 cycles × 20 ms = 1000 ms." }], answer: "T=20 ms and ω≈314 rad/s.", reasonableness: "Fifty equal cycles fit in one second." }, commonMistakes: ["Using 50 ms for 50 Hz", "Taking the reciprocal before converting ms", "Omitting 2π for angular frequency"], application: "Frequency sets motor speed relationships, reactance, filter response, timing, and oscilloscope setup.", safety: "Frequency affects physiological response, impedance, heating, and instrument bandwidth; low frequency does not make hazardous voltage safe.", knowledgeCheck: { question: "What is the period of 400 Hz?", answer: "2.5 ms", feedback: "1/400 s = 0.0025 s." }, practicalExercise: "Calculate periods for 1 Hz, 60 Hz, 1 kHz, and 20 kHz and order them longest to shortest.", summary: ["Frequency and period are reciprocals", "One hertz is one cycle per second", "Angular frequency includes 2π"]
  }),
  "electrical-fundamentals:l27": make({
    purpose: "Describe phase difference between equal-frequency sinusoids using time, degrees, and radians.", prerequisites: ["Sine waves", "Period", "Angles"], objectives: ["Define phase difference", "Convert time shift to degrees", "Identify lead and lag", "Avoid comparing phase at different frequencies"], introduction: "Phase states where one periodic waveform is in its cycle relative to another waveform of the same frequency.", theory: ["One full cycle equals 360° or 2π radians. A quarter-cycle shift is 90°.", "A waveform leads if it reaches the same reference point earlier in time; it lags if later.", "A fixed phase relationship is meaningful for signals of the same frequency; otherwise their relative phase changes with time."], terms: [{ term: "Phase", meaning: "Position within a periodic cycle", symbol: "φ", unit: "° or rad" }, { term: "Lead", meaning: "Reach a reference point earlier" }, { term: "Lag", meaning: "Reach a reference point later" }], formula: { expression: "φ=360°·Δt/T = 2π·Δt/T", explanation: "Use a signed time shift and declare which signal is the reference.", units: "degrees or radians" }, workedExample: { problem: "At 50 Hz, current reaches its positive peak 5 ms after voltage.", assumptions: ["Equal-frequency sinusoids"], steps: [{ label: "Period", detail: "T=20 ms." }, { label: "Fraction", detail: "Δt/T=5/20=0.25." }, { label: "Phase", detail: "0.25×360°=90°; current lags voltage." }], answer: "Current lags voltage by 90°.", reasonableness: "Five milliseconds is one quarter of a 20 ms cycle." }, commonMistakes: ["Reversing lead and lag", "Using peak-to-peak time as period", "Assigning fixed phase to unequal frequencies"], application: "Phase matters in impedance, power factor, motors, transformers, filters, and signal timing.", safety: "Phase-to-phase measurement can expose the instrument to a much higher potential than phase-to-neutral. Use a method and probe system rated for the circuit.", knowledgeCheck: { question: "A shift of half a cycle equals what phase angle?", answer: "180° or π radians", feedback: "One full cycle is 360°." }, practicalExercise: "Sketch two same-frequency waves with a 60° shift and label clearly which one leads.", summary: ["Phase compares cycle position", "Lead means earlier", "Time shift converts through the period"]
  }),
  "electrical-fundamentals:l28": make({
    purpose: "Introduce AC impedance and phasor relationships without treating reactance as energy dissipation.", prerequisites: ["RMS values", "Phase", "Ohm's law"], objectives: ["Define impedance", "Separate resistance and reactance", "Use RMS phasor Ohm's law", "Distinguish real and reactive behaviour"], introduction: "In sinusoidal steady state, impedance extends resistance by representing both magnitude opposition and phase shift.", theory: ["Resistance dissipates average power; ideal inductors and capacitors store energy temporarily and return it, producing reactance.", "Impedance Z is complex: Z=R+jX. Its magnitude relates RMS voltage and current, while its angle gives phase.", "For series RLC, X=XL−XC and |Z|=√(R²+X²)."], terms: [{ term: "Impedance", meaning: "Complex voltage-to-current ratio", symbol: "Z", unit: "Ω" }, { term: "Reactance", meaning: "Frequency-dependent energy-storage opposition", symbol: "X", unit: "Ω" }, { term: "Phasor", meaning: "Complex representation of a sinusoid at one frequency" }], formula: { expression: "V=IZ; |Z|=√(R²+X²)", explanation: "Phasor quantities use one common sinusoidal frequency and normally RMS magnitudes.", units: "V, A, Ω" }, workedExample: { problem: "A series load has R=30 Ω and net inductive reactance X=40 Ω on 100 V RMS.", assumptions: ["Sinusoidal steady state"], steps: [{ label: "Magnitude", detail: "|Z|=√(30²+40²)=50 Ω." }, { label: "Current", detail: "I=100/50=2 A RMS." }, { label: "Angle", detail: "φ=atan(40/30)=53.1°, so current lags." }], answer: "|Z|=50 Ω; I=2 A RMS; current lags by about 53°.", reasonableness: "The 3-4-5 triangle makes impedance exceed both components." }, commonMistakes: ["Adding R and X arithmetically", "Calling reactance consumed power", "Mixing peak voltage with RMS current"], application: "Impedance underpins AC loads, filters, motors, transformers, power factor, and fault calculations.", safety: "A small measured DC resistance does not imply small AC impedance, and stored energy may remain after isolation. Follow discharge and verification procedures.", knowledgeCheck: { question: "For a purely resistive AC load, what is the voltage-current phase angle?", answer: "0°", feedback: "Resistor voltage and current are in phase." }, practicalExercise: "Find impedance magnitude and current for R=12 Ω, X=5 Ω at 26 V RMS.", summary: ["Impedance includes resistance and reactance", "Reactance shifts phase", "Use consistent RMS phasors"]
  }),
};
