export type LessonReviewState = "fully-enhanced-verified" | "preserved-verified" | "enhanced-review-pending" | "blocked";
export interface LessonReview { state: LessonReviewState; reviewedOn: string; evidence: string; }

export const LESSON_REVIEWS: Record<string, LessonReview> = {
  "electrical-fundamentals:l1": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Topic-specific structured lesson, calculation checked, deterministic atomic-model diagram added; final professional content review remains pending." },
  "electrical-fundamentals:l2": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "SI charge definitions and worked conversion checked against BIPM/NIST." },
  "electrical-fundamentals:l3": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Material model, breakdown caveat, and safety context reviewed." },
  "electrical-fundamentals:l4": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Conventional-current and carrier-direction treatment reviewed." },
  "electrical-fundamentals:l5": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific charge/carrier module quiz has a stable valid answer; retry and persisted attempt behavior covered by tests." },
  "electrical-fundamentals:l6": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured potential-difference lesson and worked example." },
  "electrical-fundamentals:l7": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured current lesson and worked example." },
  "electrical-fundamentals:l8": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured resistance and resistivity lesson." },
  "electrical-fundamentals:l9": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured Ohm-law lesson and inverse calculation checks." },
  "electrical-fundamentals:l10": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Existing 240 V heater exercise checked: 5 A, 1.2 kW, 2.4 kWh." },
  "electrical-fundamentals:l11": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Series rules, balance checks, and example verified." },
  "electrical-fundamentals:l12": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Parallel rules, branch currents, and example verified." },
  "electrical-fundamentals:l13": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Node-based series-parallel reduction and conservation checks verified." },
  "electrical-fundamentals:l14": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Unloaded divider formulas and loading caveat verified." },
  "electrical-fundamentals:l15": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific combined-network exercise checked: 6 Ω total, 2 A source current, and branch-current conservation." },
  "electrical-fundamentals:l16": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "KCL signs, node balance, and 1.5 A worked result verified." },
  "electrical-fundamentals:l17": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "KVL polarity treatment and 15 V loop balance verified." },
  "electrical-fundamentals:l18": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Mesh/nodal distinctions and 5 V node example verified." },
  "electrical-fundamentals:l19": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific Kirchhoff problem set added with current and voltage conservation checks." },
  "electrical-fundamentals:l20": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Power forms and 72 W / 43.2 kJ example verified." },
  "electrical-fundamentals:l21": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Energy unit conversions checked against SI relationships." },
  "electrical-fundamentals:l22": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Cable loss, voltage drop, and efficiency example verified." },
  "electrical-fundamentals:l23": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific power and energy quiz added with stable answer mapping." },  "electrical-fundamentals:l24": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "AC/DC comparison and transmission-loss example individually verified." },
  "electrical-fundamentals:l25": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Sine RMS, peak, and peak-to-peak relationships individually verified." },
  "electrical-fundamentals:l26": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Frequency, period, and angular-frequency conversions individually verified." },
  "electrical-fundamentals:l27": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Phase lead/lag and time-shift calculation individually verified." },
  "electrical-fundamentals:l28": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "AC impedance magnitude and phase example individually verified." },
  "electrical-fundamentals:l29": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Capacitance, stored charge, and energy example individually verified." },
  "electrical-fundamentals:l30": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Capacitive reactance and leading-current example individually verified." },
  "electrical-fundamentals:l31": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Inductance construction and stored-energy example individually verified." },
  "electrical-fundamentals:l32": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Inductive reactance and lagging-current example individually verified." },
  "electrical-fundamentals:l33": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "RC/RL time constants and one-tau landmark individually verified." },
  "electrical-fundamentals:l34": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Multimeter connection, true-RMS, and CAT-system guidance individually reviewed." },
  "electrical-fundamentals:l35": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Clamp placement, cancellation, sensor type, and live-work cautions individually reviewed." },
  "electrical-fundamentals:l36": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Oscilloscope scale, probe-factor, sampling, and grounding guidance individually reviewed." },
  "electrical-fundamentals:l37": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Final assessment replaced with a course-specific RMS/reactance question and stable answer mapping." },
  "domestic-wiring:l1": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Consumer-unit functional layout and neutral/CPC routing individually reviewed." },
  "domestic-wiring:l2": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "MCB overload, instantaneous characteristic, breaking-capacity, and Zs workflow individually reviewed." },
  "domestic-wiring:l3": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "RCCB/RCBO functional distinctions and circuit-division consequences individually reviewed." },
  "domestic-wiring:l4": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Split-load, shared-RCD, and all-RCBO architecture trade-offs individually reviewed." },
  "domestic-wiring:l5": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Module quiz replaced with a consumer-unit-specific RCCB/RCBO question and stable answer mapping." },
  "domestic-wiring:l6": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Ring topology, current-sharing assumptions, and broken-ring risk individually reviewed." },
  "domestic-wiring:l7": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Ring-final cable-selection workflow and limitations individually reviewed." },
  "domestic-wiring:l8": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Fused/unfused spur topology and downstream protection individually reviewed." },
  "domestic-wiring:l9": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Radial topology and section-current example individually verified." },
  "domestic-wiring:l10": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Generic exercise replaced with a domestic ring/radial topology analysis and explicit non-approval limitation." },
  "domestic-wiring:l11": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Junction-box and loop-in conductor paths, joint accessibility, and CPC continuity individually reviewed." },
  "domestic-wiring:l12": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "One-way switching path, polarity, identification, and verification workflow individually reviewed." },
  "domestic-wiring:l13": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Two-way changeover states, common/strapper roles, and terminal variation individually reviewed." },
  "domestic-wiring:l14": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Intermediate straight/crossed paths and multi-position topology individually reviewed." },
  "domestic-wiring:l15": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "LED driver/dimmer compatibility, loading, inrush, and derating individually reviewed." },
  "domestic-wiring:l16": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Lighting quiz replaced with a two-way switching state question and stable answer mapping." },
  "domestic-wiring:l17": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "TN-S, TN-C-S, TT, PE/PEN, and fault-return distinctions individually reviewed against 2026 guidance." },
  "domestic-wiring:l18": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Main protective bonding purpose and extraneous-part classification individually reviewed." },
  "domestic-wiring:l19": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Supplementary-bonding scope and conditional omission workflow individually reviewed." },
  "domestic-wiring:l20": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "TT electrode design, RA/RCD coordination, hazards, and measurement limitations individually reviewed." },
  "domestic-wiring:l21": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Bonding quiz replaced with an extraneous-conductive-part classification question and stable answer mapping." },
  "domestic-wiring:l22": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Bathroom zone geometry, equipment suitability, RCD, and Amendment 4 distance caveats individually reviewed." },
  "domestic-wiring:l23": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Kitchen loads, accessory duty, isolation, routes, and external influences individually reviewed." },
  "domestic-wiring:l24": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Outbuilding load, submain, exported-earth, PEN-risk, and verification workflow individually reviewed." },
  "domestic-wiring:l25": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Outdoor ingress, RCD, burial, mechanical, and excavation controls individually reviewed." },
  "domestic-wiring:l26": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Twin-and-earth construction, CPC sizing, identification, and sheath limitations individually reviewed." },
  "domestic-wiring:l27": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Concealed wall zones, RCD, mechanical protection, and structural constraints individually reviewed." },
  "domestic-wiring:l28": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Containment fill, bend, grouping, segregation, earthing, and fire-stopping individually reviewed." },
  "domestic-wiring:l29": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Void routing, thermal insulation, supports, structure, and fire penetrations individually reviewed." },
  "domestic-wiring:l30": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Depths and zones quiz replaced with a concealed-route/RCD distinction and stable answer mapping." },
  "domestic-wiring:l31": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Evidence-led fault process, safe boundaries, hypothesis tests, and post-repair verification individually reviewed." },
  "domestic-wiring:l32": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Open line, neutral, CPC, backfeed, and continuity localisation individually reviewed." },
  "domestic-wiring:l33": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Short, earth-fault, cross-connection, borrowed-neutral, and insulation-test workflow individually reviewed." },
  "domestic-wiring:l34": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "RCD leakage, cumulative current, N-E faults, device type, and circuit division individually reviewed." },
  "domestic-wiring:l35": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Generic exercise replaced with a two-circuit shared-neutral fault case and safe diagnostic sequence." },
  "domestic-wiring:l36": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "BS 7671 structure, normative/informative roles, Part 7 interaction, and Amendment 4 transition individually reviewed." },
  "domestic-wiring:l37": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "EIC, MEIWC, EICR, declaration, test-record, and notification distinctions individually reviewed." },
  "domestic-wiring:l38": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "England Part P scope, notification, competent-person, building-control, and jurisdiction limits individually reviewed." },
  "domestic-wiring:l39": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Final assessment replaced with a certification/notification distinction and stable answer mapping." },
  "protection-fault-analysis:l1": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Rewirable/cartridge fuse construction, replacement, breaking, I²t, and legacy risks individually reviewed." },
  "protection-fault-analysis:l2": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "B/C/D thermal-instantaneous curves, inrush, fault-current, Zs, and device-data workflow individually reviewed." },
  "protection-fault-analysis:l3": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "RCBO residual/overcurrent functions, neutral routing, type, ratings, and verification individually reviewed." },
  "protection-fault-analysis:l4": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "AFDD arc signatures, application scope, limitations, coordination, and indicator handling individually reviewed." },
  "protection-fault-analysis:l5": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Device-selection quiz replaced with a B-to-C curve/Zs coordination question and stable answer mapping." },
  "protection-fault-analysis:l6": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Fault-loop path, Ze/R1+R2/Zs, fault current, TN/TT, and ADS concepts individually reviewed." },
  "protection-fault-analysis:l7": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Ze boundary, DNO evidence, parallel paths, abnormal results, and live-test limitations individually reviewed." },
  "protection-fault-analysis:l8": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Calculated/measured Zs, temperature bases, uncertainty, device limit, and evidence reconciliation individually reviewed." },
  "protection-fault-analysis:l9": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Table 41.1 context, circuit/system classification, Ia, RCD method, and non-universal timing individually reviewed." },
  "protection-fault-analysis:l10": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Generic exercise replaced with a temperature-aware Zs design and exact-device verification workflow." },
  "protection-fault-analysis:l11": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "RCD core balance, residual-current paths, neutral/CPC routing, and limitations individually reviewed." },
  "protection-fault-analysis:l12": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Type AC/A/F/B waveform capability, DC blinding, manufacturer selection, and naming distinctions individually reviewed." },
  "protection-fault-analysis:l13": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "IΔn purpose, leakage margin, delay, fault/additional/fire protection, and selectivity individually reviewed." },
  "protection-fault-analysis:l14": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Current RCD test sequence, optional diagnostics, leakage effects, instrument limits, and restoration individually reviewed." },
  "protection-fault-analysis:l15": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "RCD-selection quiz replaced with a Type B RCD versus B-curve MCB distinction and stable answer mapping." },
  "protection-fault-analysis:l16": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "PEFC/PSCC/PFC scope, source contributions, point dependence, and equipment capability individually reviewed." },
  "protection-fault-analysis:l17": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Origin PFC calculation, correct loop, DNO enquiry, low-impedance uncertainty, and live-test limits individually reviewed." },
  "protection-fault-analysis:l18": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Downstream Thevenin/feeder impedance, fault basis, temperature/reactance, and local sources individually reviewed." },
  "protection-fault-analysis:l19": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Breaking/withstand/conditional ratings, backup data, assembly capability, and source configuration individually reviewed." },
  "protection-fault-analysis:l20": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Generic PFC exercise replaced with origin/downstream calculation and uncertainty/capability gates." },
  "protection-fault-analysis:l21": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Selectivity, partial selectivity, backup protection, fault-range, and paired-device evidence individually reviewed." },
  "protection-fault-analysis:l22": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Current pickup, tolerance envelopes, instantaneous overlap, and selectivity limits individually reviewed." },
  "protection-fault-analysis:l23": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Time grading, total clearing, margin, high-set overlap, and withstand constraints individually reviewed." },
  "protection-fault-analysis:l24": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "I-squared-t, peak let-through, fuse distinctions, and manufacturer-specific MCB coordination individually reviewed." },
  "protection-fault-analysis:l25": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Generic exercise replaced with a paired-device selectivity case that prevents approval from current-rating ratio alone." },
  "protection-fault-analysis:l26": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Zs evidence options, no-trip limitations, parallel paths, uncertainty, and live-test controls individually reviewed." },
  "protection-fault-analysis:l27": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Board PFC fault bases, low-impedance uncertainty, source contributions, and equipment capability individually reviewed." },
  "protection-fault-analysis:l28": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Current RCD trip-time sequence, waveform settings, leakage, records, and restoration individually reviewed." },
  "protection-fault-analysis:l29": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Final assessment replaced with a selectivity-versus-backup distinction and stable answer mapping." },
  "three-phase-systems:l1": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Three-phase symmetry, aggregate power, conductor-use qualification, and unbalance caveats individually reviewed." },
  "three-phase-systems:l2": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Winding displacement, induced emf, pole-count frequency, and 4-pole 1500 rpm example individually verified." },
  "three-phase-systems:l3": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Phase sequence, cyclic-order equivalence, pair-swap reversal, and live-test controls individually reviewed." },
  "three-phase-systems:l4": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Balanced phasors, reference convention, rectangular conversion, and zero vector sum individually verified." },
  "three-phase-systems:l5": { state: "preserved-verified", reviewedOn: "2026-08-22", evidence: "Generic quiz replaced with a phase-sequence pair-swap question and stable answer mapping." },
  "three-phase-systems:l6": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Star topology, line/phase current equality, neutral role, and floating-star risk individually reviewed." },
  "three-phase-systems:l7": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Root-three line-voltage derivation, 30-degree displacement, and 230-to-398 V calculation individually verified." },
  "three-phase-systems:l8": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Neutral phasor sum, unbalance example, triplen harmonics, and neutral safety individually reviewed." },
  "three-phase-systems:l9": { state: "preserved-verified", reviewedOn: "2026-08-22", evidence: "Generic exercise replaced with a balanced-star voltage, current, neutral, and power analysis with explicit assumptions." },
  "three-phase-systems:l10": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Delta topology, phase/line voltage, branch/line current, and sequence-path qualifications individually reviewed." },
  "three-phase-systems:l11": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Root-three delta line-current derivation, 30-degree displacement, and 12-to-20.8 A example individually verified." },
  "three-phase-systems:l12": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Circulating-current causes, balanced fundamental cancellation, triplen paths, and paralleling risks individually reviewed." },
  "three-phase-systems:l13": { state: "preserved-verified", reviewedOn: "2026-08-22", evidence: "Generic exercise replaced with a balanced-delta branch current, line current, and total-power analysis." },
  "three-phase-systems:l14": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Balanced active, reactive, and apparent power formulas and 400 V, 20 A, 0.80 PF example individually verified." },
  "three-phase-systems:l15": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "True versus displacement power factor, current impact, distortion, and representative measurement individually reviewed." },
  "three-phase-systems:l16": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Two-wattmeter topology, algebraic signs, balanced-load PF limitation, and 8/2 kW example individually verified." },
  "three-phase-systems:l17": { state: "enhanced-review-pending", reviewedOn: "2026-08-22", evidence: "Correction kvar, star/delta capacitance basis, switching, discharge, and harmonic resonance individually reviewed." },
  "three-phase-systems:l18": { state: "preserved-verified", reviewedOn: "2026-08-22", evidence: "Generic quiz replaced with a three-phase P-Q-S numerical question and stable answer mapping." },
};
