export type LessonReviewState = "fully-enhanced-verified" | "preserved-verified" | "enhanced-review-pending" | "blocked";
export interface LessonReview { state: LessonReviewState; reviewedOn: string; evidence: string; }

export const LESSON_REVIEWS: Record<string, LessonReview> = {
  "electrical-fundamentals:l1": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Topic-specific structured lesson, calculation checked, deterministic atomic-model diagram added; final professional content review remains pending." },
  "electrical-fundamentals:l2": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "SI charge definitions and worked conversion checked against BIPM/NIST." },
  "electrical-fundamentals:l3": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Material model, breakdown caveat, and safety context reviewed." },
  "electrical-fundamentals:l4": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Conventional-current and carrier-direction treatment reviewed." },
  "electrical-fundamentals:l5": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific charge/carrier module quiz has a stable valid answer; retry and persisted attempt behavior covered by tests." },
  "electrical-fundamentals:l6": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured potential-difference lesson and worked example." },
  "electrical-fundamentals:l7": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured current lesson and worked example." },
  "electrical-fundamentals:l8": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured resistance and resistivity lesson." },
  "electrical-fundamentals:l9": { state: "enhanced-review-pending", reviewedOn: "2026-08-14", evidence: "Structured Ohm-law lesson and inverse calculation checks." },
  "electrical-fundamentals:l10": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Existing 240 V heater exercise checked: 5 A, 1.2 kW, 2.4 kWh." },
  "electrical-fundamentals:l11": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Series rules, balance checks, and example verified." },
  "electrical-fundamentals:l12": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Parallel rules, branch currents, and example verified." },
  "electrical-fundamentals:l13": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Node-based series-parallel reduction and conservation checks verified." },
  "electrical-fundamentals:l14": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Unloaded divider formulas and loading caveat verified." },
  "electrical-fundamentals:l15": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific combined-network exercise checked: 6 Ω total, 2 A source current, and branch-current conservation." },
  "electrical-fundamentals:l16": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "KCL signs, node balance, and 1.5 A worked result verified." },
  "electrical-fundamentals:l17": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "KVL polarity treatment and 15 V loop balance verified." },
  "electrical-fundamentals:l18": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Mesh/nodal distinctions and 5 V node example verified." },
  "electrical-fundamentals:l19": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific Kirchhoff problem set added with current and voltage conservation checks." },
  "electrical-fundamentals:l20": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Power forms and 72 W / 43.2 kJ example verified." },
  "electrical-fundamentals:l21": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Energy unit conversions checked against SI relationships." },
  "electrical-fundamentals:l22": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Cable loss, voltage drop, and efficiency example verified." },
  "electrical-fundamentals:l23": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Topic-specific power and energy quiz added with stable answer mapping." },  "electrical-fundamentals:l24": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "AC/DC comparison and transmission-loss example individually verified." },
  "electrical-fundamentals:l25": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Sine RMS, peak, and peak-to-peak relationships individually verified." },
  "electrical-fundamentals:l26": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Frequency, period, and angular-frequency conversions individually verified." },
  "electrical-fundamentals:l27": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Phase lead/lag and time-shift calculation individually verified." },
  "electrical-fundamentals:l28": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "AC impedance magnitude and phase example individually verified." },
  "electrical-fundamentals:l29": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Capacitance, stored charge, and energy example individually verified." },
  "electrical-fundamentals:l30": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Capacitive reactance and leading-current example individually verified." },
  "electrical-fundamentals:l31": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Inductance construction and stored-energy example individually verified." },
  "electrical-fundamentals:l32": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Inductive reactance and lagging-current example individually verified." },
  "electrical-fundamentals:l33": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "RC/RL time constants and one-tau landmark individually verified." },
  "electrical-fundamentals:l34": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Multimeter connection, true-RMS, and CAT-system guidance individually reviewed." },
  "electrical-fundamentals:l35": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Clamp placement, cancellation, sensor type, and live-work cautions individually reviewed." },
  "electrical-fundamentals:l36": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Oscilloscope scale, probe-factor, sampling, and grounding guidance individually reviewed." },
  "electrical-fundamentals:l37": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Final assessment replaced with a course-specific RMS/reactance question and stable answer mapping." },
  "domestic-wiring:l1": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Consumer-unit functional layout and neutral/CPC routing individually reviewed." },
  "domestic-wiring:l2": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "MCB overload, instantaneous characteristic, breaking-capacity, and Zs workflow individually reviewed." },
  "domestic-wiring:l3": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "RCCB/RCBO functional distinctions and circuit-division consequences individually reviewed." },
  "domestic-wiring:l4": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Split-load, shared-RCD, and all-RCBO architecture trade-offs individually reviewed." },
  "domestic-wiring:l5": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Module quiz replaced with a consumer-unit-specific RCCB/RCBO question and stable answer mapping." },
  "domestic-wiring:l6": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Ring topology, current-sharing assumptions, and broken-ring risk individually reviewed." },
  "domestic-wiring:l7": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Ring-final cable-selection workflow and limitations individually reviewed." },
  "domestic-wiring:l8": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Fused/unfused spur topology and downstream protection individually reviewed." },
  "domestic-wiring:l9": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Radial topology and section-current example individually verified." },
  "domestic-wiring:l10": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Generic exercise replaced with a domestic ring/radial topology analysis and explicit non-approval limitation." },
  "domestic-wiring:l11": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Junction-box and loop-in conductor paths, joint accessibility, and CPC continuity individually reviewed." },
  "domestic-wiring:l12": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "One-way switching path, polarity, identification, and verification workflow individually reviewed." },
  "domestic-wiring:l13": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Two-way changeover states, common/strapper roles, and terminal variation individually reviewed." },
  "domestic-wiring:l14": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Intermediate straight/crossed paths and multi-position topology individually reviewed." },
  "domestic-wiring:l15": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "LED driver/dimmer compatibility, loading, inrush, and derating individually reviewed." },
  "domestic-wiring:l16": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Lighting quiz replaced with a two-way switching state question and stable answer mapping." },
  "domestic-wiring:l17": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "TN-S, TN-C-S, TT, PE/PEN, and fault-return distinctions individually reviewed against 2026 guidance." },
  "domestic-wiring:l18": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Main protective bonding purpose and extraneous-part classification individually reviewed." },
  "domestic-wiring:l19": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Supplementary-bonding scope and conditional omission workflow individually reviewed." },
  "domestic-wiring:l20": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "TT electrode design, RA/RCD coordination, hazards, and measurement limitations individually reviewed." },
  "domestic-wiring:l21": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Bonding quiz replaced with an extraneous-conductive-part classification question and stable answer mapping." },
  "domestic-wiring:l22": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Bathroom zone geometry, equipment suitability, RCD, and Amendment 4 distance caveats individually reviewed." },
  "domestic-wiring:l23": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Kitchen loads, accessory duty, isolation, routes, and external influences individually reviewed." },
  "domestic-wiring:l24": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Outbuilding load, submain, exported-earth, PEN-risk, and verification workflow individually reviewed." },
  "domestic-wiring:l25": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Outdoor ingress, RCD, burial, mechanical, and excavation controls individually reviewed." },
  "domestic-wiring:l26": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Twin-and-earth construction, CPC sizing, identification, and sheath limitations individually reviewed." },
  "domestic-wiring:l27": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Concealed wall zones, RCD, mechanical protection, and structural constraints individually reviewed." },
  "domestic-wiring:l28": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Containment fill, bend, grouping, segregation, earthing, and fire-stopping individually reviewed." },
  "domestic-wiring:l29": { state: "enhanced-review-pending", reviewedOn: "2026-08-21", evidence: "Void routing, thermal insulation, supports, structure, and fire penetrations individually reviewed." },
  "domestic-wiring:l30": { state: "preserved-verified", reviewedOn: "2026-08-21", evidence: "Depths and zones quiz replaced with a concealed-route/RCD distinction and stable answer mapping." },
};
